spec:
  template:
    spec:
      containers:
        - volumeMounts:
            - name: config
              mountPath: /app/config
          env:
            - name: JAVA_OPTIONS
              value: "-Dswarm.project.stage.file=file:///app/config/project-defaults.yml"
      volumes:
        - configMap:
            name: app-config
            items:
            - key: "app-config.yml"
              path: "project-defaults.yml"
          name: config
